import type { Metadata } from 'next';
import Header from './components/Layout/Header';
import './globals.css'; // 글로벌 CSS 가져오기

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                {/* <Header /> */}
                {children}
            </body>
        </html>
    );
}
