services:
    vemo:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '5051:5050'
        command: npm run start:dev

        volumes:
            - ./src:/usr/src/app/src
        environment:
            - NODE_ENV=development
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DATABASE=${DB_DATABASE}
