services:
    vemo:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '5051:5050'
        command: npm run start:dev
        environment:
            - NODE_ENV=development
        volumes:
            - ./src:/usr/src/app/src
